<a href="https://colab.research.google.com/github/valentinptr/pytorch_learning/blob/main/00_pytorch_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import torch

In [33]:
RANDOM_SEED = 0

In [34]:
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7, 7)
tensor_A

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [35]:
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(1, 7)
tensor_B

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [36]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [37]:
torch.cuda.device("cuda")

In [38]:
RANDOM_SEED = 1234

In [39]:
torch.cuda.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7, 7)
tensor_A

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [40]:
torch.cuda.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(1, 7)
tensor_B

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])

In [41]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [42]:
torch.cuda.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(2,3, device="cuda")
tensor_C

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [43]:
torch.cuda.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(2,3, device="cuda")
tensor_D

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

In [44]:
output = torch.matmul(tensor_C, tensor_D.T)
output

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

In [45]:
max = torch.argmax(output)
max

tensor(3, device='cuda:0')

In [46]:
min = torch.argmin(output)
min

tensor(1, device='cuda:0')

In [47]:
torch.cuda.manual_seed(RANDOM_SEED)
final_tensor = torch.rand(1, 1, 1, 10)
final_tensor

tensor([[[[0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801, 0.1147,
           0.3168, 0.6965]]]])

In [48]:
final_tensor_squezzed = torch.squeeze(final_tensor)
final_tensor_squezzed

tensor([0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801, 0.1147, 0.3168,
        0.6965])

In [49]:
print("First tensor", final_tensor)
print("First tensor's shape", final_tensor.shape)
print("Second tensor", final_tensor_squezzed)
print("Second tensor's shape", final_tensor_squezzed.shape)

First tensor tensor([[[[0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801, 0.1147,
           0.3168, 0.6965]]]])
First tensor's shape torch.Size([1, 1, 1, 10])
Second tensor tensor([0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801, 0.1147, 0.3168,
        0.6965])
Second tensor's shape torch.Size([10])
